# NT14 change:
# Sprite folders here that have been changed to use NT14-specific sprites have
# base folder equilvalents that can be removed to save space if/when space wizards upstream is no longer used

- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 #4 hrs
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers

- type: startingGear
  id: MimeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMime
    back: ClothingBackpackMimeFilled
    head: ClothingHeadHatBeret
    belt: ClothingBeltSuspenders
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    mask: ClothingMaskMime
    id: MimePDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtMime
  satchel: ClothingBackpackSatchelMimeFilled
  duffelbag: ClothingBackpackDuffelMimeFilled

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  noSpawn: true
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon: NT14/Structures/Walls/solid.rsi/full.png
    event: !type:InvisibleWallActionEvent
